## torch.randn(rows, cols)

In [2]:
import torch

x0 = torch.randn(5, 2)
x0

tensor([[-0.0099, -0.2338],
        [ 0.7707, -1.1672],
        [ 1.6627,  1.4071],
        [-1.4407, -0.4199],
        [-0.1443,  0.4287]])

## torch.cat([tensor1, tensor2], dim)

In [3]:
x1 = torch.randn(5, 2)

# dim=0 operate down the rows, across cols
# (10, 2): changes row
vert = torch.cat([x0, x1], dim=0)
vert

tensor([[-0.0099, -0.2338],
        [ 0.7707, -1.1672],
        [ 1.6627,  1.4071],
        [-1.4407, -0.4199],
        [-0.1443,  0.4287],
        [ 0.1906,  0.8119],
        [-1.4406,  0.2768],
        [ 0.3436,  0.9094],
        [-0.8552,  1.8666],
        [-0.2832, -0.9620]])

In [5]:
# dim=1 operate across the cols, within each row
# (5, 4): changes col
horiz = torch.cat([x0, x1], dim=1)
horiz

tensor([[-0.0099, -0.2338,  0.1906,  0.8119],
        [ 0.7707, -1.1672, -1.4406,  0.2768],
        [ 1.6627,  1.4071,  0.3436,  0.9094],
        [-1.4407, -0.4199, -0.8552,  1.8666],
        [-0.1443,  0.4287, -0.2832, -0.9620]])

## requires_grad=True
- tells PyTorch to track a tensor for automatic differentiation

In [12]:
W1 = torch.randn(4, 2, requires_grad=True)
W2 = torch.randn(4, 2)
x = torch.randn(2, 4)

y1 = (W1 @ x).sum()
y2 = (W2 @ x).sum()
y1.backward()
# error: y2.backward()

print(W1.grad)
print(W2.grad)

tensor([[-1.2510,  0.2350],
        [-1.2510,  0.2350],
        [-1.2510,  0.2350],
        [-1.2510,  0.2350]])
None


## torch.clamp(tensor, min, max)
- clamp to avoid log(0)

In [18]:
z = torch.randn(2, 2) * 10
print(z)

clamp = torch.clamp(z, -5, 5)
print(clamp)

tensor([[ -8.2506,  -0.4817],
        [-14.9823,   3.5555]])
tensor([[-5.0000, -0.4817],
        [-5.0000,  3.5555]])


## torch.log(tensor)
- base e
- loge(x) = ln(x)
    - ln(0) = -inf
    - ln(1) = 0
    - ln(2) = 0.6931

In [21]:
t = torch.tensor([[1, 2],
                  [1, 2]])
print(t)
log = torch.log(t)
print(log)

tensor([[1, 2],
        [1, 2]])
tensor([[0.0000, 0.6931],
        [0.0000, 0.6931]])
