## Numpy ndarray (for math and no gradients)
- general scientific computing on CPU
- no built-in gradients
- manual nns
- SciPy, scikit-learn, pandas, matplotlib
## Pytorch Tensor (for GPU acceleration and autograd)
- deep learning and tensor match on CPU and GPU
- requires_grad=True, automatic backprop (autograd)
- modules for nns: nn, optim, DataLoader

### CPU (Central Processing Unit)
- few tasks at once
    - general purpose

### GPU (Graphics Processing Unit)
- many small tasks at once
    - like matrix multiplications in deep learning

In [1]:
import numpy as np

x = np.random.randn(3, 2)
x

array([[-0.27872697,  0.61780114],
       [-0.44446921, -0.53913512],
       [ 0.05870961,  0.12816029]])

In [5]:
# first row
print(x[0, :])

# third row
print(x[2, :])

# index error: print(x[4, :])

[-0.27872697  0.61780114]
[0.05870961 0.12816029]


In [6]:
# first col
print(x[:, 0])

# second col
print(x[:, 1])

[-0.27872697 -0.44446921  0.05870961]
[ 0.61780114 -0.53913512  0.12816029]


In [8]:
x[1, 1]

np.float64(-0.5391351184052131)

In [11]:
y = np.random.randn(6, 6)
print(y)

# rows 1, 2 and cols 3, 4
y[1:3, 3:5]

[[ 0.65976946  0.72157623  1.37577007  0.45959778 -1.51427195  0.19932787]
 [ 0.15956171  1.28009603 -1.61748646 -0.24772118  0.15602883 -1.30762491]
 [-1.01194583  0.41604107 -1.3851743   0.11143299  1.78424355  1.33088719]
 [ 0.55538857 -0.44117701 -0.88476334  0.34986214  0.93956562  1.4992289 ]
 [ 0.01418329  1.30866949  0.64411636  0.43915192 -2.05787426 -1.75010523]
 [ 0.59933002  0.34790839  0.5239151   1.11898509  0.37166819  1.78878765]]


array([[-0.24772118,  0.15602883],
       [ 0.11143299,  1.78424355]])

In [15]:
# reshapes into given number of rows and columns
z = y.reshape(12, 3)
print(x)

# has to have same number of elements
# value error: a = y.reshape(2, 2)

[[-0.27872697  0.61780114]
 [-0.44446921 -0.53913512]
 [ 0.05870961  0.12816029]]


In [21]:
# array of given number of zeros
a1 = np.zeros(2)
print(a1)

# matriz of zeros, has to be in tuple
b1 = np.zeros((2, 2))
print(b1)

[0. 0.]
[[0. 0.]
 [0. 0.]]


In [35]:
arr = np.random.randn(2, 2)
print(arr)

# sum all elements
print(arr.sum())

# replaces all elements with max of current element or 0
# so negatives become 0
print(np.maximum(arr, 0))

print(np.exp(arr))

[[-0.30288421  0.05624404]
 [ 1.13549473 -1.14670268]]
-0.25784812270284796
[[0.         0.05624404]
 [1.13549473 0.        ]]
[[0.73868463 1.05785581]
 [3.11271311 0.31768254]]


## Matrix Addition
- add each element elementwise
    - (2 x 3) + (2 x 3) -> 2 x 3
- broadcasting
    - (2 x 3) + (1 x 3) -> (2 x 3)
    - (2 x 3) + (2 x 1) -> (2 x 3)
    - adding biases (1 x n) to a batch (m x n) works automatically
- A + B = B + A

In [30]:
A = np.random.rand(2, 3)
B = np.random.rand(2, 3)
C = A + B
D = B + A
print(A.shape)
print(B.shape)
print(C)
print(C.shape)
print(D)
print(D.shape)

(2, 3)
(2, 3)
[[0.71738514 1.05872219 0.83736537]
 [1.11551162 0.8890593  0.10662393]]
(2, 3)
[[0.71738514 1.05872219 0.83736537]
 [1.11551162 0.8890593  0.10662393]]
(2, 3)


In [34]:
A = np.random.rand(2, 3)
B = np.random.rand(1, 3)
C = np.random.rand(2, 1)

print(A + B)
print(A + C)

[[0.76072504 0.75189813 0.30777848]
 [0.82032629 0.14067714 0.70370944]]
[[0.65654149 1.28584692 0.6833983 ]
 [0.30596695 0.26445014 0.66915346]]


## Matrix Multiplication (@ or np.dot)
- the inner dimensions must match
    - yes: (2 x 4) @ (4 x 2) = (2, 2)
    - no: (2 x 3) @ (2 x 4)

- row-col multiplication (2 x 4) @ (4 x 2)
    - first row with all columns
    - second row with all columns
    1. row 1 of A with col 1 of B
    2. row 1 of A with col 2 of B
    3. row 2 of A with col 1 of B
    4. row 2 of A with col 2 of B

- A x B != B x A

In [29]:
A = np.random.randn(2, 4)
B = np.random.randn(4, 2)
C = A @ B
D = B @ A
print(A.shape)
print(B.shape)
print(C)
print(C.shape)
print(D)
print(D.shape)

(2, 4)
(4, 2)
[[-2.76255661 -0.92527852]
 [ 1.29401888 -0.20477171]]
(2, 2)
[[-0.29446533 -0.06452548 -1.43451425  0.18756028]
 [-2.85462899 -1.66929334  1.00132123  1.15262894]
 [ 0.24291973  0.18820601 -0.74442555 -0.06865123]
 [ 0.77578037  0.53847919 -1.48370764 -0.25914411]]
(4, 4)
